export function renderAiLayoutGuide(): string {
    return [
        '# AI Layout Guide for SiYuan',
        '',
        'Use this guide when you need to turn user intent into a well-structured SiYuan note rather than plain text.',
        '',
        '## Decision order',
        '',
        '1. Start with normal structure blocks first: headings, paragraphs, lists, task lists, blockquotes, callouts, tables, math blocks, and fenced code blocks.',
        '2. Escalate to Kramdown super blocks only when the user needs side-by-side comparison, cards, or dashboard-like layouts.',
        '3. Use block attributes only for metadata or styling, not for structural layout.',
        '4. Use renderer code-block languages when the user wants visual output such as diagrams, charts, mind maps, or music notation.',
        '5. Use media, embeds, HTML, or database blocks only when the user benefits from embedded playback, live views, or structured records.',
        '6. Prefer native SiYuan structures over plain paragraphs whenever they improve readability.',
        '7. Do not confuse layout, metadata, rendering, and database layers.',
        '',
        '## Native structure blocks',
        '',
        '- Headings, paragraphs, unordered lists, ordered lists, task lists, blockquotes, callouts, tables, math blocks, and fenced code blocks are the default safe building blocks.',
        '- Callouts come from Markdown like `> [!TIP]` or `> [!IMPORTANT]` and are stored as `type = "callout"`.',
        '- Common callout markers are `NOTE`, `TIP`, `IMPORTANT`, `WARNING`, and `CAUTION`.',
        '- Use headings plus lists for most note-taking tasks; this is the default layout baseline.',
        '- Use tables for lightweight structured display. A Markdown table is not the same thing as a real SiYuan database block.',
        '- Tags belong in block markdown as `#tag#`; hierarchical tags use forms such as `#project/phase#`.',
        '',
        '## Formatting elements inventory',
        '',
        '- Inline elements include links, images, bold, italic, underline, strikethrough, highlight, superscript, subscript, `kbd`, inline code, inline math, inline remarks, tags, IAL-based color/effect spans, and emoji.',
        '- Block elements include headings, paragraphs, unordered lists, ordered lists, task lists, blockquotes, callouts, code blocks, tables, HTML blocks, thematic breaks, math blocks, iframe, video, audio, super blocks, and query embeds.',
        '- Renderable code blocks include `mindmap`, `flowchart`, Mermaid `graph`, Mermaid `sequenceDiagram`, Mermaid `gantt`, Mermaid `classDiagram`, Mermaid `journey`, Mermaid `gitGraph`, Mermaid `erDiagram`, `echarts`, `abc`, `graphviz`, and `plantuml`.',
        '- Treat the inventory as a menu of native expression choices, not as a requirement to flatten everything into paragraphs.',
        '',
        '## Kramdown layout',
        '',
        '- Super blocks are real SiYuan blocks with `type = "s"`.',
        '- Horizontal and nested layouts come from nested Kramdown blocks such as `{{{col` and `{{{row`.',
        '- Use super blocks for side-by-side comparison, card grids, split summaries, pros/cons, and dashboard-like sections.',
        '- Super block layout comes from Kramdown, not from block attributes.',
        '- For a horizontal multi-column layout, use an outer `{{{col` and put one child `{{{row` block per column.',
        '- For vertical stacking inside one column, place multiple blocks inside that column\'s child `{{{row`.',
        '- There is no separator-based super block syntax; `===` inside a super block is not a column delimiter.',
        '',
        '### Correct syntax shortcuts',
        '',
        '- Super blocks: use nested `{{{col` and `{{{row` blocks with matching `}}}`. Do not use `::: row`, HTML `<div>`, or `===` as a super block substitute or delimiter.',
        '- Pattern: horizontal columns usually mean outer `{{{col` + one child `{{{row` per column.',
        '- Pattern: each child `{{{row` can contain multiple ordinary blocks stacked vertically.',
        '- Colors: prefer inline attribute lists such as `**text**{: style="color: var(--b3-font-color1);"}` or `**text**{: style="color: var(--b3-font-color1); background-color: var(--b3-font-background1);"}`.',
        '- Callouts: use Markdown like `> [!NOTE]`, `> [!TIP]`, `> [!WARNING]`, `> [!IMPORTANT]`, and `> [!CAUTION]`.',
        '- Remarks: use inline HTML like `<sup>note</sup>` only for small annotations, not for main layout.',
        '',
        '## Block attributes',
        '',
        '- Use block attributes for metadata or style enhancement, not for super block layout.',
        '- Built-in attributes include `name`, `alias`, `memo`, and `bookmark`.',
        '- Custom metadata uses the `custom-*` prefix, for example `custom-status` or `custom-priority`.',
        '- Visual tweaks can use the `style` attribute, for example text alignment or bold styling.',
        '- Inline color and effect samples can also be expressed with inline attribute lists such as `{: style="color: ...; background-color: ...;"}`.',
        '',
        '## Visual code blocks',
        '',
        '- Some rich renderers are still stored as normal code blocks (`type = "c"`). The renderer is chosen by the fenced code language.',
        '- `mindmap`: mind maps.',
        '- `mermaid`: Mermaid diagrams including flow charts (`graph`), sequence diagrams (`sequenceDiagram`), gantt charts (`gantt`), class diagrams (`classDiagram`), Git graphs (`gitGraph`), ER diagrams (`erDiagram`), and journey diagrams (`journey`).',
        '- `flowchart`: Flowchart.js syntax.',
        '- `graphviz`: Graphviz syntax.',
        '- `plantuml`: PlantUML syntax.',
        '- `echarts`: ECharts config blocks; JSON, JavaScript object literals, and IIFE-returned objects are all valid patterns.',
        '- `abc`: abcjs music notation; `%%params ...` may appear at the top.',
        '- Treat these as renderable note structures, not as ordinary code examples, when the user wants visual output.',
        '',
        '## Media, HTML, embeds, and databases',
        '',
        '- Video, audio, iframe, and HTML are distinct rich blocks, not ordinary code fences.',
        '- Their block content is usually stored as HTML tags such as `<video>`, `<audio>`, `<iframe>`, or raw HTML fragments.',
        '- Query embeds use `{{ select ... }}` and are stored as `type = "query_embed"`.',
        '- Use query embeds for dynamic rollups, filtered views, and auto-updating reference sections.',
        '- Unless the user explicitly wants self-referential results, query embeds should exclude the current root document, for example with `root_id != "<current-doc-id>"`.',
        '- Real SiYuan database blocks use `type = "av"` and are stored as `NodeAttributeView` containers such as `<div data-type="NodeAttributeView" ...></div>`.',
        '- Databases support records, multiple views, filters, sorts, relations, and rollups; they are not just prettier tables.',
        '- Do not describe a Markdown table as a database block, and do not describe a database block as just a table.',
        '- The dedicated MCP `av` tool can create and materialize a new database with `render(createIfNotExist=true, blockID=...)`; omit `avID` to let MCP generate the AV ID automatically.',
        '',
        '## Recommended usage rules',
        '',
        '- For ordinary summaries and notes, default to headings, lists, callouts, tables, code blocks, and math blocks.',
        '- For side-by-side comparisons or card-like layouts, actively consider super blocks.',
        '- For status, naming, aliases, bookmarks, or custom workflow data, actively consider block attributes.',
        '- For diagrams, timelines, Git history, entity relationships, journeys, charts, mind maps, and music notation, actively consider renderable code-block languages instead of plain text.',
        '- Choose the renderer language by diagram intent, not by “any renderable block is fine”: `graph` or `flowchart` for flow, `sequenceDiagram` for interactions, `gantt` for schedules, `classDiagram` for type relations, `journey` for user paths, `gitGraph` for commit history, and `erDiagram` for entities and relations.',
        '- For media playback or external embeds, use media or iframe blocks only when the user clearly benefits from embedded playback or live preview.',
        '- For structured records with real views and field semantics, use database blocks; for lightweight display only, use Markdown tables.',
        '- For “collect”, “favorite”, or “save for later” semantics on an existing block, consider the `bookmark` attribute rather than inventing a tag.',
        '- For flashcards, prefer `flashcard(action="create_card")`; raw block attributes such as `custom-riff-decks` are only the metadata half of the workflow.',
        '',
        '## Common daily formatting decisions',
        '',
        '- When the user asks for a diary entry, journal, daily log, or today’s note in a notebook, prefer `document(action="create_daily_note")` over manually creating a path and then appending content.',
        '- When the user is organizing notes, summaries, meeting minutes, or plans, prefer headings, paragraphs, lists, task lists, tables, and callouts over one long paragraph.',
        '- When the user wants comparison, side-by-side information, cards, dashboards, pros/cons, or parallel summaries, actively consider super blocks instead of forcing everything into plain lists or tables.',
        '- When the user wants reminders, warnings, key conclusions, tips, or highlighted takeaways, actively consider callouts instead of plain blockquotes or bold-only paragraphs.',
        '- When the user wants flow, sequence, timeline, project scheduling, class relations, Git evolution, metrics trends, mind maps, or music notation, actively consider the corresponding renderer code-block language instead of ordinary code samples.',
        '- When the user wants lightweight field display, use Markdown tables; when the user wants structured records, multiple views, filters, relations, or rollups, use database blocks instead.',
        '- When the user wants categorization, topic labels, or future retrieval, actively consider tags written in markdown.',
        '- When the user wants collect, favorite, or save-for-later semantics on an existing block, actively consider the `bookmark` attribute instead of inventing a tag.',
        '- When the user wants review, memorization, Q&A, or cloze-style learning, actively consider flashcard semantics, but keep flashcards separate from layout choice.',
        '- In normal day-to-day use, choose the simplest native SiYuan structure that matches the user intent while preserving the correct semantics.',
        '',
        '## Example everyday mappings',
        '',
        '- Daily note or diary: use `document(action="create_daily_note")` for the notebook first, then write content into that returned document.',
        '- Meeting notes: headings for agenda, lists for points, task lists for follow-ups, and callouts for decisions or risks.',
        '- Project comparison: super blocks for side-by-side sections, tables for quick field comparison, and callouts for conclusions.',
        '- Knowledge cards: headings for the topic, concise bullet points, small remarks where needed, and tags for retrieval.',
        '- Data tracking: database blocks for structured records and multiple views; Markdown tables only for lightweight display.',
        '- Personal curation: tags for categorization, bookmarks for collecting existing blocks worth revisiting later.',
        '',
        '## Usage semantics from the official guide',
        '',
        '- Bookmarks are for collecting existing blocks and are exposed in SiYuan as a block-level saved item concept.',
        '- Tags are inline markdown tokens such as `#tag#`; hierarchical tags use forms such as `#A/B/C#`.',
        '- Avoid special-symbol-heavy bookmark or tag names when searchability and global management matter.',
        '- Flashcards are scheduled-review artifacts; creating a good note layout and marking a flashcard are separate steps.',
        '- SiYuan flashcard interpretation rules include: marked text `==answer==` as a cloze answer, a super block with the first child as the question, a heading with following blocks as the answer, and a list or list item with child lists treated as the answer area.',
        '- Through MCP, prefer producing final note content or block attributes directly instead of narrating UI-only steps unless the user explicitly asks how to use the built-in SiYuan interface.',
        '- If the user asks how SiYuan built-in AI works, explain that the official entry is the AI settings page plus commands such as `/AI 编写` or block-menu AI actions, and note that related text may be sent to an external model service.',
        '',
        '## Confusion pairs',
        '',
        '- A blockquote is not a block reference.',
        '- A query embed is not a static block list or an ordinary reference.',
        '- Raw HTML `<div>` is not a super block substitute.',
        '- `===` is not a super block column delimiter.',
        '- A Markdown table is not a real `av` database block.',
        '- A bookmark is not a tag.',
        '- A flashcard is not a layout type.',
        '',
        '## Anti-confusion rules',
        '',
        '- `::: row` is not valid SiYuan super block syntax.',
        '- Raw HTML `<div>` is not a substitute for super blocks.',
        '- `===` inside a super block is parsed as a separate element rather than a column delimiter.',
        '- Inline `<span style="color: ...">` is not the preferred color-marking pattern when `{: style="..."}` can express the same intent.',
        '- Super block layout is defined by Kramdown, not block attributes.',
        '- Database blocks are `type = "av"`, not Markdown tables.',
        '- Mermaid, Flowchart, Graphviz, PlantUML, ECharts, ABC, and mindmap are renderer languages attached to code blocks.',
        '- Video, audio, iframe, and HTML blocks are richer than plain paragraphs or code fences and should be chosen intentionally.',
        '- Tags are literal markdown tokens like `#tag#`, not block attributes.',
        '- Bookmarks are block attributes, not inline tags.',
        '- Flashcards are not a layout type; they are review semantics attached to blocks.',
    ].join('\n');
}
